name: Android - Release to Google Play

on:
  workflow_dispatch:

jobs:
  call_get_vars:
    uses: ./.github/workflows/get-vars.yml  

  call_reusable_workflow:
    needs: call_get_vars
    uses: IDEMSInternational/open-app-builder-actions/.github/workflows/android-release.yml@main
    with:
      APP_CODE_BRANCH: ${{ vars.APP_CODE_BRANCH }}
      APP_ID: ${{ needs.call_get_vars.outputs.APP_ID }}
      LFS_USED: ${{ needs.call_get_vars.outputs.LFS_USED == 'true' }}
      DEPLOYMENT_NAME: ${{ needs.call_get_vars.outputs.DEPLOYMENT_NAME }}
      PARENT_DEPLOYMENT_NAME: ${{ needs.call_get_vars.outputs.PARENT_DEPLOYMENT_NAME }}
      PARENT_DEPLOYMENT_REPO: ${{ needs.call_get_vars.outputs.PARENT_DEPLOYMENT_REPO }}
      PARENT_DEPLOYMENT_BRANCH: ${{ needs.call_get_vars.outputs.PARENT_DEPLOYMENT_BRANCH }}
      ENCRYPTED: ${{ needs.call_get_vars.outputs.ENCRYPTED == 'true' }} 
    secrets:
      DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}  
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}  
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}  
      ALIAS: ${{ secrets.ALIAS }}  
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}  
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}  
      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}  
