##################################################################################
#         Calls workflow from code repo
##################################################################################
name: Android - Release to Google Play

on:
  workflow_dispatch:

jobs:
  sync_content:
    uses: IDEMSInternational/parenting-app-ui/.github/workflows/reusable-android-release.yml@master
    secrets: inherit
