##################################################################################
#         Configuration
##################################################################################
env:
  # Secrets
  GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
  SIGNING_KEY: ${{secrets.SIGNING_KEY}}
  ALIAS: ${{secrets.ALIAS}}
  KEY_STORE_PASSWORD: ${{secrets.KEY_STORE_PASSWORD}}
  KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}

##################################################################################
#         Main Code
##################################################################################
name: Android Build

# Only keep one active build per ref (e.g. pr branch, push branch, triggering workflow ref)
concurrency:
  group: android-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
jobs:

#############################################################################
#         Build web
#############################################################################
  web_build:
    uses: ./.github/workflows/app-build.yml
    with:
      artifact-name: www
    secrets: inherit

#############################################################################
#         Build android
#############################################################################    
  build_android:
    runs-on: ubuntu-latest
    needs: build_action
    env:
      GIT_SHA: ${{ needs.build_action.outputs.GIT_SHA }}
    steps:
    ##Not sure if this is needed?
  
    #  - uses: actions/checkout@v3
    #    with:
    #      ref:  ${{ inputs.branch }}
    #  - name: Checkout git lfs partial files
    #    run: git lfs pull --include "android/*"
      - name: Check out app code
        uses: actions/checkout@v3
        with:
          repository: "IDEMSInternational/parenting-app-ui.git"
          ref: ${{env.APP_CODE_BRANCH}}
      - name: Checkout git lfs partial files
        run: git lfs pull --include "android/*"


    
      #############################################################################
      #         Configure
      # Setup node same way as web build to allow calling `npx cap sync` command
      #############################################################################

      - name: Populate google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ env.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      #############################################################################
      #         Sync web files
      # Setup node same way as web build to allow calling `npx cap sync` command
      #############################################################################
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x          
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-yarn-v1-
            
      - name: Install node modules
        run: yarn install --immutable
      
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: www
          
      - name: Extract Build folder
        run: |
          mkdir www
          tar -xf artifact.tar --directory www
          
      - name: Sync Android Files
        run: npx cap sync
      #############################################################################
      #         Android Build
      #############################################################################
        # Java version mapping: https://stackoverflow.com/a/47457251/5693245
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          java-package: jdk
          cache: "gradle"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

        # Signed Release Bundle
      - name: Build Android Release Bundle
        working-directory: android
        run: ./gradlew :app:bundleRelease

      - name: Sign Android Release
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ env.SIGNING_KEY }}
          alias: ${{ env.ALIAS }}
          keyStorePassword: ${{ env.KEY_STORE_PASSWORD }}
          keyPassword: ${{ env.KEY_PASSWORD }}
          
      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: release_bundle
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}
