env:
  ANDROID_APP_ID: ${{vars.ANDROID_APP_ID}}


# When creating a release in GitHub, create android release AAB and debug APK
# files and upload to release files
name: Android - Release to Google Play
# on:
#   release:
#     types: [published]
on:
  workflow_dispatch:
  
jobs:
  build:
    uses: ./.github/workflows/android-build.yml
    secrets: inherit
    
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: release_bundle
          path: ./

      - name: Upload to Google play
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{env.ANDROID_APP_ID}}
          releaseFile: ${{steps.download.outputs.download-path}}/app-release.aab
          track: internal
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
